<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\SmartMetrix.Contracts\SmartMetrix.Contracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\SmartMetrix.ServiceDefaults\SmartMetrix.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="native\smartmetrix_arena.h" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="simulator-frames\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
