import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Station } from '../station.mjs';
function fixture(t) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'rtk-test-')); t.after(() => fs.rmSync(dir, { recursive: true, force: true })); let time = 0; const file = path.join(dir, 'state.json'); return { station: new Station(file, () => time), file, advance: ms => time += ms }; }
const coords = { lat: 42.87, lon: 74.56, height: 812.4 };
function ready(s) { s.action('manual', coords); s.action('confirm'); s.action('start'); }
test('Start requires coordinates; relocation invalidates old location even after restart', t => { const { station: s, file } = fixture(t); assert.throws(() => s.action('start')); ready(s); s.action('relocate'); assert.equal(s.status().running, false); assert.throws(() => s.action('start')); const rebooted = new Station(file); assert.equal(rebooted.status().coordinates, null); assert.throws(() => rebooted.action('start')); });
test('Survey cannot be confirmed early and remains stopped until explicit start', t => { const { station: s, advance } = fixture(t); s.action('survey', { duration: 15 }); assert.throws(() => s.action('confirm')); advance(15000); assert.equal(s.status().candidate.source, 'simulated-average'); assert.throws(() => s.action('start')); s.action('confirm'); assert.equal(s.status().running, false); s.action('start'); assert.equal(s.status().running, true); });
test('USB and satellite faults stop stream and require manual restart', t => { const { station: s } = fixture(t); ready(s); for (const kind of ['usb', 'signal']) { s.action('fault', { kind }); assert.equal(s.status().rate, 0); assert.throws(() => s.action('start')); s.action('fault', { kind }); assert.equal(s.status().running, false); s.action('start'); } });
test('Fault cancels averaging instead of producing false result', t => { const { station: s, advance } = fixture(t); s.action('survey', { duration: 15 }); s.action('fault', { kind: 'usb' }); advance(20000); assert.equal(s.status().candidate, null); assert.equal(s.status().survey, null); });
test('Profiles and settings persist; stream never auto-starts after restart', t => { const { station: s, file } = fixture(t); ready(s); s.action('save-profile', { name: 'Мастерская' }); s.action('stop'); s.action('settings', { mountpoint: 'WORKSHOP', port: 2101 }); const rebooted = new Station(file); assert.equal(rebooted.status().profiles.length, 1); assert.equal(rebooted.status().settings.mountpoint, 'WORKSHOP'); assert.equal(rebooted.status().running, false); rebooted.action('relocate'); rebooted.action('load-profile', { id: rebooted.status().profiles[0].id }); assert.throws(() => rebooted.action('start')); rebooted.action('confirm'); rebooted.action('start'); });
test('Invalid coordinates and changing coordinates during streaming are rejected', t => { const { station: s } = fixture(t); for (const input of [{ ...coords, lat: '' }, { ...coords, lat: 91 }, { ...coords, lon: 181 }, { ...coords, height: null }, { ...coords, lat: 'NaN' }]) assert.throws(() => s.action('manual', input)); ready(s); assert.throws(() => s.action('manual', coords)); assert.throws(() => s.action('settings', { mountpoint: 'NEW', port: 2101 })); });
